<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FirebaseAdmin" Version="2.2.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.52.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core.DomainModel\Core.Domain.csproj" />
    <ProjectReference Include="..\Colaboracao.Core\Colaboracao.Core.csproj" />
    <ProjectReference Include="..\Firebase.Domain\Firebase.Domain.csproj" />
  </ItemGroup>
</Project>