 CREATE TABLE tb_perfil_corporativo (
  id 									char(36) NOT NULL,
  tb_org_id 							int NOT NULL,
  descricao             				varchar(255) NOT NULL,
  tb_permanencia_id     				char(36) DEFAULT NULL,
  tb_modelo_trabalho_id 				char(36) DEFAULT NULL,
  tb_profissional_localidade_id 		char(36) DEFAULT NULL,
  tipo_emprego_linkedin 				char(36) DEFAULT NULL,
  nivel_experiencia_linkedin 			char(36) DEFAULT NULL,
  atribuicoes 							text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  codigo_interno_colaborador_criacao   	varchar(36) DEFAULT NULL,
  codigo_interno_colaborador_alteracao 	varchar(36) DEFAULT NULL,
  data_criacao   						timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  data_alteracao 						timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ativo 								tinyint DEFAULT 1,
  PRIMARY KEY (id),
  KEY idx_pfcorp_orgid (id, tb_org_id), 
  CONSTRAINT fk_pfcorp_orgid FOREIGN KEY (tb_org_id) REFERENCES tb_org (id),
  CONSTRAINT fk_pfcorp_permanenciaid FOREIGN KEY (tb_permanencia_id) REFERENCES tb_permanencia (id),
  CONSTRAINT fk_pfcorp_modelotrabalhoid FOREIGN KEY (tb_modelo_trabalho_id) REFERENCES tb_modelo_trabalho (id),
  CONSTRAINT fk_pfcorp_profissionallocalidadeid FOREIGN KEY (tb_profissional_localidade_id) REFERENCES tb_profissional_localidade (id),
  CONSTRAINT fk_pfcorp_tiposempregolinkedin FOREIGN KEY (tipo_emprego_linkedin) REFERENCES tb_tipos_emprego_linkedin (id),
  CONSTRAINT fk_pfcorp_niveisexperiencialinkedin FOREIGN KEY (nivel_experiencia_linkedin) REFERENCES tb_niveis_experiencia_linkedin (id),
  CONSTRAINT fk_pfcorp_codintcolaboradorcriacao   FOREIGN KEY (codigo_interno_colaborador_criacao)   REFERENCES tb_colaborador (codigo_interno_colaborador),
  CONSTRAINT fk_pfcorp_codintcolaboradoralteracao FOREIGN KEY (codigo_interno_colaborador_alteracao) REFERENCES tb_colaborador (codigo_interno_colaborador)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
