CREATE TABLE tb_solicitacao_reembolso (
      id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
      tb_org_id INT NOT NULL,
      tb_projeto_id VARCHAR(255) NOT NULL,
      tb_cliente_id VARCHAR(45) NOT NULL,
      tb_verba_id INT NOT NULL,
      codigo_interno_colaborador VARCHAR(36) NOT NULL,
      descricao VARCHAR(300),
      data_despesa TIMESTAMP NOT NULL,
      valor DECIMAL(10,2) NOT NULL,
      valor_unidade DECIMAL(10,2) DEFAULT NULL,
      quantidade INT DEFAULT NULL,
      status_id INT NOT NULL,
      data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      data_alteracao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      codigo_interno_colaborador_criacao VARCHAR(36) NOT NULL,
      codigo_interno_colaborador_edicao VARCHAR(36) DEFAULT NULL,
      codigo_interno_colaborador_aprovador VARCHAR(36) DEFAULT NULL,
    
      CONSTRAINT fk_reembolso_org FOREIGN KEY (tb_org_id) REFERENCES tb_org(id),
      CONSTRAINT fk_reembolso_projeto FOREIGN KEY (tb_projeto_id) REFERENCES tb_projeto_org(cod_projeto),
      CONSTRAINT fk_reembolso_cliente FOREIGN KEY (tb_cliente_id) REFERENCES tb_cliente_org(codigo_cliente),
      CONSTRAINT fk_reembolso_verba FOREIGN KEY (tb_verba_id) REFERENCES tb_verba(id),
      CONSTRAINT fk_reembolso_colab FOREIGN KEY (codigo_interno_colaborador) REFERENCES tb_colaborador(codigo_interno_colaborador),
      CONSTRAINT fk_reembolso_colab_criacao FOREIGN KEY (codigo_interno_colaborador_criacao) REFERENCES tb_colaborador(codigo_interno_colaborador),
      CONSTRAINT fk_reembolso_colab_edicao FOREIGN KEY (codigo_interno_colaborador_edicao) REFERENCES tb_colaborador(codigo_interno_colaborador),
      CONSTRAINT fk_reembolso_colab_aprovacao FOREIGN KEY (codigo_interno_colaborador_aprovador) REFERENCES tb_colaborador(codigo_interno_colaborador),
      CONSTRAINT fk_reembolso_status FOREIGN KEY (status_id) REFERENCES tb_solicitacao_status(id)
);