INSERT INTO tb_permanencia (id, descricao, ativo) 
VALUES  (UUID(), 'Até 4 anos', 1),
	    (UUID(), 'Até 5 anos', 1),
	    (UUID(), 'Até 6 anos', 1),
	    (UUID(), 'Até 7 anos', 1),
	    (UUID(), 'Até 8 anos', 1),
	    (UUID(), 'Até 9 anos', 1),
	    (UUID(), 'Até 10 anos', 1),
	    (UUID(), 'Até 11 anos', 1),
	    (UUID(), 'Até 12 anos', 1),
	    (UUID(), 'Até 13 anos', 1),
	    (UUID(), 'Até 14 anos', 1),
	    (UUID(), 'Até 15 anos', 1),
	    (UUID(), 'Até 16 anos', 1),
	    (UUID(), 'Até 17 anos', 1),
	    (UUID(), 'Até 18 anos', 1),
	    (UUID(), 'Até 19 anos', 1),
	    (UUID(), 'Até 20 anos', 1),
	    (UUID(), 'Até 21 anos', 1),
	    (UUID(), 'Mais de 21 anos', 1);
