<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>71a453ce-82d1-49b9-bee0-e2d4b3ec3cf4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Controller\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MockServer.Application\MockServer.Application.csproj" />
    <ProjectReference Include="..\MockServer.Domain\MockServer.Domain.csproj" />
  </ItemGroup>
</Project>