INSERT INTO tb_cidadania(descricao)
VALUES
('Americana / Americano'),
('Alandesa / Alandês'),
('Anguilhana / Anguilhano'),
('Antártica'),
('Bermudiana / Bermudiano'),
('Camaronesa / Camaronês'),
('Canalense / Canalês'),
('Catariana / Catariano'),
('Comoriana / Comoriano'),
('Gibraltina / Gibraltino'),
('Guameana / Guameano'),
('Guatemalteca / Guatemalteco'),
('Hongkonguês / Hongkonguês'),
('Ilhas Malvinas / Falklandense'),
('Ilhas Virgens Britânicas / Virginiano Britânico'),
('Jamaicana / Jamaicano'),
('Madeirense'),
('Maldiviana / Maldiviano'),
('Mauriciana / Mauriciano'),
('Montserratiana / Montserratiano'),
('Nepalesa / Nepalês'),
('Nicaraguense'),
('Palestina / Palestino'),
('Porto-riquenha / Porto-riquenho'),
('Reunionense / Reunionês'),
('Seychellois / Seichelense'),
('Taiti / Taitiano'),
('Terceirense'),
('Tokelauano'),
('Vanuatuense / Vanuatuano');