
ALTER TABLE `tb_competencia` 
CHANGE COLUMN `data_alteracao` `data_alteracao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ;
ALTER TABLE `tb_softskill` 
CHANGE COLUMN `data_alteracao` `data_alteracao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ;
ALTER TABLE `tb_idioma` 
CHANGE COLUMN `data_alteracao` `data_alteracao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ;
ALTER TABLE `tb_dominionegocio` 
CHANGE COLUMN `data_alteracao` `data_alteracao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ;
ALTER TABLE `tb_metodologia` 
CHANGE COLUMN `data_alteracao` `data_alteracao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ;
