<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Colaboracao.Helper\Colaboracao.Helper.csproj" />
    <ProjectReference Include="..\Competencia.Domain\Competencia.Domain.csproj" />
    <ProjectReference Include="..\Core.DomainModel\Core.Domain.csproj" />
    <ProjectReference Include="..\DataTransferObject.Domain\DataTransferObject.Domain.csproj" />
    <ProjectReference Include="..\Colaboracao.Core\Colaboracao.Core.csproj" />
    <ProjectReference Include="..\Colaboracao.Helper\Colaboracao.Helper.csproj" />
    <ProjectReference Include="..\Foursys.Domain\Foursys.Domain.csproj" />
    <ProjectReference Include="..\Labs.Domain\Labs.Domain.csproj" />
    <ProjectReference Include="..\Logs.Infra\Logs.Infra.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.20" />
  </ItemGroup>
</Project>