<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Colaboracao.Core\Colaboracao.Core.csproj" />
    <ProjectReference Include="..\Colaboracao.Infra\Colaboracao.Infra.csproj" />
    <ProjectReference Include="..\Usuario.Domain\Usuario.Domain.csproj" />
    <ProjectReference Include="..\Colaboracao.Initializer\Colaboracao.Initializer.csproj" />
    <ProjectReference Include="..\Logs.Infra\Logs.Infra.csproj" />
  </ItemGroup>
</Project>