CREATE TABLE `tb_colaborador_dados_demograficos` (
  `id` varchar(36) NOT NULL COMMENT 'GUID dos dados demográficos',
  `codigo_interno_colaborador` varchar(36) NOT NULL COMMENT 'Chave estrangeira para tb_colaborador',
  `quantidade_pessoas_residencia` int NOT NULL DEFAULT 1 COMMENT 'Mora com quantas pessoas? (mínimo 1)',
  `dependentes_irpf` int NOT NULL DEFAULT 0 COMMENT 'Dependentes IRRF (mínimo 0)',
  `possui_conjuge` tinyint NOT NULL DEFAULT 0 COMMENT 'Possui cônjuge/companheiro(a)?',
  `data_nascimento_conjuge` date DEFAULT NULL COMMENT 'Data de Nascimento do Cônjuge',
  `possui_filhos` tinyint NOT NULL DEFAULT 0 COMMENT 'Possui filhos?',
  `possui_seguro_saude` tinyint NOT NULL DEFAULT 0 COMMENT 'Possui seguro saúde?',
  `valor_atual_seguro_saude` decimal(10,2) DEFAULT NULL COMMENT 'Valor Atual do Seguro Saúde (R$)',
  `operadora_seguro_saude` varchar(255) DEFAULT NULL COMMENT 'Operadora do Seguro Saúde',
  `acomodacao_seguro_saude` varchar(50) DEFAULT NULL COMMENT 'Acomodação: Apartamento, Enfermaria',
  `seguro_saude_possui_coparticipacao` tinyint NOT NULL DEFAULT 0 COMMENT 'Possui coparticipação?',
  `observacoes_seguro_saude` text DEFAULT NULL COMMENT 'Observações do Seguro Saúde',
  `possui_interesse_plano_foursys` tinyint NOT NULL DEFAULT 0 COMMENT 'Possui interesse no plano Foursys?',
  `faixa_etaria` varchar(50) DEFAULT NULL COMMENT 'Faixa Etária',
  `categoria_plano_saude` varchar(50) DEFAULT NULL COMMENT 'Categoria do Plano: general, supervisor, executive',
  `incluir_dependentes_plano_foursys` tinyint NOT NULL DEFAULT 0 COMMENT 'Incluir dependentes no plano Foursys?',
  `quantidade_dependentes_plano_foursys` int NOT NULL DEFAULT 0 COMMENT 'Quantidade de Dependentes no Plano Foursys',
  `valor_plano_dependentes` decimal(10,2) DEFAULT NULL COMMENT 'Valor do Plano Dependentes (R$)',
  `valor_cartao_refeicao` decimal(10,2) DEFAULT NULL COMMENT 'Cartão Refeição (R$) - constante: 660',
  `valor_cartao_alimentacao` decimal(10,2) DEFAULT NULL COMMENT 'Cartão Alimentação (R$)',
  `estuda_atualmente` tinyint NOT NULL DEFAULT 0 COMMENT 'Estuda atualmente?',
  `custo_mensal_educacao` decimal(10,2) DEFAULT NULL COMMENT 'Custo Mensal com Educação (R$)',
  `filhos_estudam_ate_24_anos` tinyint NOT NULL DEFAULT 0 COMMENT 'Filhos (até 24 anos) estudam?',
  `custo_mensal_educacao_filhos` decimal(10,2) DEFAULT NULL COMMENT 'Custo Mensal com Educação dos Filhos (R$)',
  `custo_total_educacao` decimal(10,2) DEFAULT NULL COMMENT 'Custo Total Educação (R$) - derivado',
  `distancia_ida_volta` decimal(10,2) DEFAULT NULL COMMENT 'Distância (Ida/Volta) em km',
  `data_criacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_alteracao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_codigo_interno_colaborador` (`codigo_interno_colaborador`),
  KEY `fk_tb_colaborador_dados_demograficos_tb_colaborador_idx` (`codigo_interno_colaborador`),
  CONSTRAINT `fk_tb_colaborador_dados_demograficos_tb_colaborador` FOREIGN KEY (`codigo_interno_colaborador`) REFERENCES `tb_colaborador` (`codigo_interno_colaborador`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='Dados demográficos do colaborador';
