ALTER TABLE tb_solicitacao_reembolso
    ADD COLUMN objetivo VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN destino VARCHAR(255) DEFAULT NULL,
    ADD COLUMN data_inicio DATETIME DEFAULT NULL,
    ADD COLUMN data_fim DATETIME DEFAULT NULL;