namespace DataTransferObject.Domain.Fourmakers
{
    public enum ParametroOrgCodigoEnum
    {
        ASSOCIACAO_AUTOMATICA_COLABORADOR_PROJETO,
        CONFIGURACAO_API_SOAP_LG,
        PERMITIR_LANCAMENTO_MAIOR_24_HORAS,
        PERMITIR_SOBREPOSICAO_ALOCACOES,
        HABILITAR_RELATORIO_APONTAMENTO_SIMPLIFICADO,
        DEVE_INCLUIR_INATIVOS_MAPA_ALOCACAO,
        DEVE_PULAR_GERENCIA_CLIENTES_PROJETO,
        DEVE_ASSOCIAR_GRUPO_ACESSO_POR_CONFIGURACAO,
        CONFIGURACAO_PERCENTUAL_ADERENCIA,
        CAMPOS_NAO_OBRIGATORIOS_CADASTRO_COLABORADOR,
        CONFIGURACAO_PERCENTUAL_MATCH_REVERSO,
        CONFIGURACAO_ADERENCIA_ORG,
        CADASTRA_CLIENTE_OCULTO_NA_GESTAO_ALOCADOS,
        PERMITIR_APROVADOR_APONTAR_SEUS_LANCAMENTOS,
        OCULTAR_MODULO_TIMESHEET_MODELO_CONTRATACAO,
        CONFIGURACAO_APONTAMENTO_EXCEDENTE_VALOR,
        APONTAMENTO_EXCEDENTE_DESTINATARIOS,
        ANIVERSARIANTE_PROXIMOS_DIAS_QUANTIDADE,
        ANIVERSARIANTE_OCULTA_EMAIL,
        CONSIDERAR_APENAS_ATIVOS_RELATORIO_APONTAMENTO_SIMPLIFICADO,
        REEMBOLSO_HABILITAR_REMESSA_CNAB,
        NOTA_FISCAL_HABILITAR_REMESSA_CNAB,
    }

    public enum ParametroOrgCodigoFrontEndEnum
    {
        LABEL_COLABORADOR_TIMESHEET,
        LABEL_COLABORADORES_TIMESHEET,
        REEMBOLSO_COLETA_DADOS_BANCARIOS,
        REEMBOLSO_PERMITIR_SOLICITACAO_SEM_PROJETO,
        REEMSOLBO_WORKFLOW_APROVACAO_CFO
    }
}