<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ApiClient.Domain\ApiClient.Domain.csproj" />
    <ProjectReference Include="..\Colaboracao.Shared.CargaCore.Domain\Colaboracao.Shared.CargaCore.Domain.csproj" />
    <ProjectReference Include="..\Colaboracao.Core\Colaboracao.Core.csproj" />
    <ProjectReference Include="..\Colaboracao.Helper\Colaboracao.Helper.csproj" />
    <ProjectReference Include="..\Core.DomainModel\Core.Domain.csproj" />
    <ProjectReference Include="..\DataTransferObject.Domain\DataTransferObject.Domain.csproj" />
    <ProjectReference Include="..\Colaboracao.Helper\Colaboracao.Helper.csproj" />
    <ProjectReference Include="..\Foursys.Domain\Foursys.Domain.csproj" />
    <ProjectReference Include="..\Projeto.Domain\Projeto.Domain.csproj" />
    <ProjectReference Include="..\SRS.Domain\SRS.Domain.csproj" />
    <ProjectReference Include="..\Labs.Domain\Labs.Domain.csproj" />
    <ProjectReference Include="..\Logs.Infra\Logs.Infra.csproj" />
  </ItemGroup>
</Project>