CREATE TABLE `tb_colaborador_periodo_alocacao` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `data_inicio` timestamp NOT NULL,
  `data_fim` timestamp NOT NULL,
  `quantidade_horas` double NOT NULL,
  `inclui_fimdesemana` tinyint NOT NULL DEFAULT '0',
  `ativo` tinyint NOT NULL DEFAULT '1',
  `data_criacao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_alteracao` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `observacao` text,
  `oportunidade` text,
  `prioritario` tinyint DEFAULT '0',
  `percentual` double DEFAULT NULL,
  `codigo_colaborador` varchar(255) DEFAULT NULL,
  `codigo_projeto` varchar(255) NOT NULL,
  `tb_colaborador_cpf` varchar(11) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `tb_org_id` int NOT NULL,
  `cod_tbd_alocado` int DEFAULT NULL,
  `tb_atividade_id` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_tb_colaborador_periodo_alocacao_tb_colaborador1_idx` (`tb_colaborador_cpf`),
  KEY `fk_tb_colaborador_periodo_alocacao_tb_org1_idx` (`tb_org_id`),
  KEY `fk_tb_colaborador_periodo_alocacao_tb_atividade_idx` (`tb_atividade_id`),
  KEY `fk_tb_colaborador_periodo_alocacao_tb_tbd_alocado_idx` (`cod_tbd_alocado`),
  CONSTRAINT `fk_tb_colaborador_periodo_alocacao_tb_colaborador1` FOREIGN KEY (`tb_colaborador_cpf`) REFERENCES `tb_colaborador` (`cpf`),
  CONSTRAINT `fk_tb_colaborador_periodo_alocacao_tb_org1` FOREIGN KEY (`tb_org_id`) REFERENCES `tb_org` (`id`),
  CONSTRAINT `fk_tb_colaborador_periodo_alocacao_tb_atividade` FOREIGN KEY (`tb_atividade_id`) REFERENCES `tb_atividade` (`id`),
  CONSTRAINT `fk_tb_colaborador_periodo_alocacao_tb_tbd_alocado` FOREIGN KEY (`cod_tbd_alocado`) REFERENCES `tb_tbd_alocado` (`cod_tbd_alocado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
