CREATE TABLE tb_verba_personalizada (
  id INT NOT NULL AUTO_INCREMENT,
  tb_verba_id INT NOT NULL,
  tb_org_id INT NOT NULL,
  cliente_id VARCHAR(255) DEFAULT NULL,
  projeto_id VARCHAR(255) DEFAULT NULL,
  codigo_interno_colaborador VARCHAR(36) DEFAULT NULL,
  valor_customizado DECIMAL(10,2) NOT NULL,
  custo_cliente TINYINT(1) NOT NULL DEFAULT 1,
  ativo TINYINT(1) NOT NULL,
  deletado TINYINT(1) DEFAULT 0,
  desativado_em TIMESTAMP NULL DEFAULT NULL,
  data_criacao TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY fk_verba (tb_verba_id),
  KEY fk_org (tb_org_id),
  KEY fk_cliente (cliente_id),
  KEY fk_projeto (projeto_id),
  KEY fk_colaborador (codigo_interno_colaborador),
  CONSTRAINT fk_cliente FOREIGN KEY (cliente_id) REFERENCES tb_cliente_org (codigo_cliente),
  CONSTRAINT fk_colaborador FOREIGN KEY (codigo_interno_colaborador) REFERENCES tb_colaborador (codigo_interno_colaborador),
  CONSTRAINT fk_org FOREIGN KEY (tb_org_id) REFERENCES tb_org (id),
  CONSTRAINT fk_projeto FOREIGN KEY (projeto_id) REFERENCES tb_projeto_org (cod_projeto),
  CONSTRAINT fk_verba FOREIGN KEY (tb_verba_id) REFERENCES tb_verba (id)
);