INSERT INTO tb_subcategoria_assunto (id, descricao, tb_categoria_assunto_id)
VALUES 
	(1, 'Desenvolvimento sob medida', 1),
	(2, 'Modernização de Legado', 1),
	(3, 'Arquitetura e Engenharia de Soluções', 1),
	(4, 'Sustentação e Suporte Técnico', 1),
	(5, 'Governança de TI & Arquitetura Corporativa', 1),
	(1, 'Transformação Digital', 2),
	(2, 'Org Design', 2),
	(1, 'Governança de Dados', 3),
	(2, 'Engenharia de Dados', 3),
	(3, 'Business Intelligence & Analytics', 3),
	(1, 'Alocação de Profissionais', 4),
	(2, 'Reposição de Profissionais', 4),
	(3, 'Gestão de Alocados', 4),
	(1, 'Governança, Riscos e Conformidade', 5),
	(2, 'DevSecOps e Segurança de Aplicações', 5),
	(3, 'Cibersegurança Operacional', 5),
	(4, 'Segurança em Nuvem', 5),
	(5, 'Consultoria Estratégica em Segurança', 5),
	(1, 'Prototipação e POCs', 6),
	(2, 'Experimentação com IA', 6),
	(3, 'Design de Soluções Inovadoras', 6),
	(4, 'Agentes', 6),
	(1, 'Soluções Integradas com Parceiros', 7),
	(2, 'Parcerias Educacionais', 7),
	(3, 'Startups e Inovação Aberta', 7),
	(4, 'Projetos Conjuntos com Parceiros', 7),
	(1, 'Fourmakers – Mapa de Alocação', 8),
	(2, 'Fourmakers – Timesheet', 8),
	(3, 'Fourmakers – Recrutamento & Banco de Talentos', 8),
	(4, 'Fourmakers – PDI & Minha Jornada', 8),
	(5, 'Fourmakers – Feedback 360', 8),
	(6, 'Fourmakers – Parcerias e Alianças', 8),
	(7, 'Fourmakers – Jornada de Alocados', 8),
	(8, 'Fourmakers – Conciliação de Folha', 8),
	(9, 'Fourmakers – Match de Habilidades', 8),
	(10, 'Fourmakers – Maverick (Agenda Comercial e CRM)', 8)
	;

