CREATE TABLE `tb_banco` (
  `codigo_banco` char(3) NOT NULL,
  `nome` varchar(10) NOT NULL,
  `descricao` varchar(100) NOT NULL,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`codigo_banco`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO tb_banco (codigo_banco, descricao, nome) VALUES
('001', 'Banco do Brasil S.A.', 'BB'),
('033', 'Banco Santander (Brasil) S.A.', 'Santander'),
('104', 'Caixa Econômica Federal', 'CEF'),
('237', 'Banco Bradesco S.A.', 'Bradesco'),
('341', 'Itaú Unibanco S.A.', 'Itaú'),
('356', 'Banco Real S.A.', 'Real'),
('399', 'HSBC Bank Brasil S.A.', 'HSBC'),
('745', 'Banco Citibank S.A.', 'Citi'),
('422', 'Banco Safra S.A.', 'Safra'),
('212', 'Banco Original S.A.', 'Original'),
('290', 'PagSeguro S.A.', 'PagSeguro'),
('260', 'Nu Pagamentos S.A.', 'Nubank'),
('637', 'Banco Sofisa S.A.', 'Sofisa'),
('707', 'Banco Daycoval S.A.', 'Daycoval'),
('623', 'Banco Pan S.A.', 'Pan'),
('128', 'Banco Cooperativo do Brasil S.A. - BANCOOB', 'BANCOOB'),
('652', 'Itaú Unibanco Holding S.A.', 'Itaú'),
('265', 'Banco Fator S.A.', 'Fator'),
('477', 'Citibank N.A.', 'Citibank'),
('246', 'Banco ABC Brasil S.A.', 'ABC'),
('214', 'Banco Dibens S.A.', 'Dibens');

CREATE TABLE `tb_cnab_org` (
  `id` char(36) NOT NULL,
  `tb_org_id` int NOT NULL,
  `diretoria` varchar(100) DEFAULT NULL,
  `codigo_banco` char(3) NOT NULL,
  `agencia` char(5) NOT NULL,
  `agencia_dv` char(1) DEFAULT NULL,
  `conta` char(12) NOT NULL,
  `conta_dv` char(1) NOT NULL,
  `codigo_convenio` varchar(20) DEFAULT NULL,
  `cnpj_empresa` char(14) NOT NULL,
  `forma_pagamento` enum('PIX','TED') NOT NULL,
  `data_criacao` datetime DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `nome_empresa` varchar(30) NOT NULL,
  `nome_banco` varchar(30) NOT NULL,
  `endereco_empresa` varchar(30) NOT NULL,
  `numero_local` varchar(5) NOT NULL,
  `complemento_endereco` varchar(15) DEFAULT NULL,
  `cidade` varchar(20) NOT NULL,
  `cep` char(8) NOT NULL,
  `estado` char(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_diretoria_forma` (`tb_org_id`,`diretoria`,`forma_pagamento`),
  KEY `codigo_banco` (`codigo_banco`),
  CONSTRAINT `tb_cnab_org_ibfk_1` FOREIGN KEY (`tb_org_id`) REFERENCES `tb_org` (`id`),
  CONSTRAINT `tb_cnab_org_ibfk_2` FOREIGN KEY (`codigo_banco`) REFERENCES `tb_banco` (`codigo_banco`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;