<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.2" />
    <PackageReference Include="itext7" Version="7.0.4" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="7.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="8.0.8" />
    <PackageReference Include="PdfPig" Version="0.1.10" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
    <PackageReference Include="BitMiracle.Docotic.Pdf" Version="8.1.12215" />
    <PackageReference Include="DotNetEnv" Version="2.3.0" />
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.8" />
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DataTransferObject.Domain\DataTransferObject.Domain.csproj" />
  </ItemGroup>
</Project>