INSERT INTO tb_admissao_cbo (id, codigo, titulo, descricao, ativo) VALUES
(UUID(), '2124-05', 'Analista de desenvolvimento de sistemas', 'Desenvolvem e implantam sistemas informatizados, dimensionando requisitos e funcionalidades, especificando arquitetura e codificando.', 1),
(UUID(), '2521-05', 'Administrador', 'Planejam, organizam, controlam e assessoram as organizações nas áreas de recursos humanos, patrimônio, materiais, informações, financeira, tecnológica.', 1),
(UUID(), '1423-35', 'Analista de pesquisa de mercado', 'Planejam, coordenam e executam pesquisas de mercado e de opinião pública.', 1),
(UUID(), '2124-15', 'Analista de sistemas de automação', 'Desenvolvem e implantam sistemas de automação, analisam funcionalidades e planejam testes.', 1),
(UUID(), '1423-30', 'Analista de negócios', 'Analisa processos de negócios, identifica oportunidades e propõe soluções tecnológicas ou processuais.', 1),
(UUID(), '3172-10', 'Técnico de suporte ao usuário de informática', 'Prestão suporte técnico a usuários de informática, instalam e configuram software e hardware.', 1),
(UUID(), '2524-05', 'Analista de recursos humanos', 'Atuam na administração de pessoal, recrutamento e seleção, cargos e salários, treinamento e desenvolvimento.', 1),
(UUID(), '3911-05', 'Planejador de produção', 'Planejam e controlam o fluxo de produção, materiais e recursos.', 1),
(UUID(), '3912-05', 'Inspetor de qualidade', 'Inspecionam o recebimento de matérias-primas e o processo produtivo, garantindo padrões de qualidade.', 1),
(UUID(), '2124-20', 'Analista de suporte de sistema', 'Instalam, configuram e atualizam sistemas operacionais e softwares de apoio.', 1),
(UUID(), '4110-10', 'Assistente administrativo', 'Executam serviços de apoio nas áreas de recursos humanos, administração, finanças e logística.', 1),
(UUID(), '3541-25', 'Assistente de vendas', 'Prestão assistência no processo de venda, atendendo clientes e processando pedidos.', 1),
(UUID(), '3171-10', 'Programador de sistemas de informação', 'Desenvolvem, implantam e mantêm sistemas de informação de acordo com metodologias e padrões.', 1),
(UUID(), '2624-10', 'Designer gráfico (Web Designer)', 'Projetam e desenvolvem layouts, interfaces e comunicações visuais para meios digitais ou impressos.', 1),
(UUID(), '4110-05', 'Auxiliar de escritório', 'Executam serviços de apoio administrativo e de escritório.', 1),
(UUID(), '2332-25', 'Instrutor de cursos livres', 'Ministram aulas e treinamentos em diversas áreas de cursos livres.', 1),
(UUID(), '1233-05', 'Diretor comercial', 'Formulam estratégias de vendas, definem metas e gerenciam a equipe comercial.', 1),
(UUID(), '2531-10', 'Redator de publicidade', 'Criam textos para anúncios, campanhas e materiais promocionais.', 1),
(UUID(), '1422-10', 'Gerente de recursos humanos', 'Gerenciam as atividades de RH, definindo políticas e diretrizes da área.', 1),
(UUID(), '1425-20', 'Gerente de projetos de tecnologia da informação', 'Planejam e gerenciam projetos de TI, controlando escopo, prazo e qualidade.', 1),
(UUID(), '1423-15', 'Gerente de marketing', 'Planejam e gerenciam atividades de marketing e comunicação estratégica.', 1),
(UUID(), '1425-30', 'Gerente de segurança da tecnologia da informação', 'Gerenciam a segurança da informação e a continuidade dos negócios.', 1),
(UUID(), '1421-15', 'Gerente financeiro', 'Gerenciam o planejamento e controle financeiro da organização.', 1),
(UUID(), '2332-10', 'Instrutor de aprendizagem técnica', 'Ministram aulas de formação técnica e profissionalizante.', 1),
(UUID(), '4221-05', 'Recepcionista, em geral', 'Atendem e orientam o público, realizam agendamentos e recepção de documentos.', 1),
(UUID(), '2611-40', 'Assessor de imprensa', 'Gerenciam o relacionamento da organização com os veículos de comunicação.', 1),
(UUID(), '5143-20', 'Faxineiro', 'Executam serviços de limpeza e conservação em ambientes diversos.', 1)
ON DUPLICATE KEY UPDATE 
    titulo = VALUES(titulo), 
    descricao = VALUES(descricao),
    ativo = VALUES(ativo);