update tb_subcategoria_assunto set descricao = 'Modernização de Legado' where id = 2 and tb_categoria_assunto_id = 1;
update tb_subcategoria_assunto set descricao = 'Arquitetura e Engenharia de Soluções' where id = 3 and tb_categoria_assunto_id = 1;
update tb_subcategoria_assunto set descricao = 'Sustentação e Suporte Técnico' where id = 4 and tb_categoria_assunto_id = 1;
update tb_subcategoria_assunto set descricao = 'Governança de TI & Arquitetura Corporativa' where id = 5 and tb_categoria_assunto_id = 1;
update tb_subcategoria_assunto set descricao = 'Transformação Digital' where id = 1 and tb_categoria_assunto_id = 2;
update tb_subcategoria_assunto set descricao = 'Governança de Dados' where id = 1 and tb_categoria_assunto_id = 3;
update tb_subcategoria_assunto set descricao = 'Alocação de Profissionais' where id = 1 and tb_categoria_assunto_id = 4;
update tb_subcategoria_assunto set descricao = 'Reposição de Profissionais' where id = 2 and tb_categoria_assunto_id = 4;
update tb_subcategoria_assunto set descricao = 'Gestão de Alocados' where id = 3 and tb_categoria_assunto_id = 4;
update tb_subcategoria_assunto set descricao = 'Governança, Riscos e Conformidade' where id = 1 and tb_categoria_assunto_id = 5;
update tb_subcategoria_assunto set descricao = 'DevSecOps e Segurança de Aplicações' where id = 2 and tb_categoria_assunto_id = 5;
update tb_subcategoria_assunto set descricao = 'Cibersegurança Operacional' where id = 3 and tb_categoria_assunto_id = 5;
update tb_subcategoria_assunto set descricao = 'Segurança em Nuvem' where id = 4 and tb_categoria_assunto_id = 5;
update tb_subcategoria_assunto set descricao = 'Consultoria Estratégica em Segurança' where id = 5 and tb_categoria_assunto_id = 5;
update tb_subcategoria_assunto set descricao = 'Prototipação e POCs' where id = 1 and tb_categoria_assunto_id = 6;
update tb_subcategoria_assunto set descricao = 'Experimentação com IA' where id = 2 and tb_categoria_assunto_id = 6;
update tb_subcategoria_assunto set descricao = 'Design de Soluções Inovadoras' where id = 3 and tb_categoria_assunto_id = 6;
update tb_subcategoria_assunto set descricao = 'Soluções Integradas com Parceiros' where id = 1 and tb_categoria_assunto_id = 7;
update tb_subcategoria_assunto set descricao = 'Startups e Inovação Aberta' where id = 3 and tb_categoria_assunto_id = 7;
update tb_subcategoria_assunto set descricao = 'Fourmakers - Mapa de Alocação' where id = 1 and tb_categoria_assunto_id = 8;
update tb_subcategoria_assunto set descricao = 'Fourmakers - Timesheet' where id = 2 and tb_categoria_assunto_id = 8;
update tb_subcategoria_assunto set descricao = 'Fourmakers - Recrutamento & Banco de Talentos' where id = 3 and tb_categoria_assunto_id = 8;
update tb_subcategoria_assunto set descricao = 'Fourmakers - PDI & Minha Jornada' where id = 4 and tb_categoria_assunto_id = 8;
update tb_subcategoria_assunto set descricao = 'Fourmakers - Feedback 360' where id = 5 and tb_categoria_assunto_id = 8;
update tb_subcategoria_assunto set descricao = 'Fourmakers - Parcerias e Alianças' where id = 6 and tb_categoria_assunto_id = 8;
update tb_subcategoria_assunto set descricao = 'Fourmakers - Jornada de Alocados' where id = 7 and tb_categoria_assunto_id = 8;
update tb_subcategoria_assunto set descricao = 'Fourmakers – Conciliação de Folha' where id = 8 and tb_categoria_assunto_id = 8;
update tb_subcategoria_assunto set descricao = 'Fourmakers – Match de Habilidades' where id = 9 and tb_categoria_assunto_id = 8;
update tb_subcategoria_assunto set descricao = 'Fourmakers – Maverick (Agenda Comercial e CRM)' where id = 10 and tb_categoria_assunto_id = 8;

