<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>76514805-d1a8-4716-8ddb-147ae46dcba2</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HttpMultipartParser" Version="6.0.1" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Colaboracao.Core\Colaboracao.Core.csproj" />
    <ProjectReference Include="..\DataTransferObject.Domain\DataTransferObject.Domain.csproj" />
    <ProjectReference Include="..\UploadFiles.Application\UploadFiles.Application.csproj" />
    <ProjectReference Include="..\UploadFiles.Domain\UploadFiles.Domain.csproj" />
  </ItemGroup>
</Project>