<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Controllers\GestaoDesempenho\nul" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Colaboracao.Initializer\Colaboracao.Initializer.csproj" />
      <ProjectReference Include="..\GestaoPessoa.Application\GestaoPessoa.Application.csproj" />
      <ProjectReference Include="..\GestaoPessoa.Domain\GestaoPessoa.Domain.csproj" />
    </ItemGroup>

</Project>
