ALTER TABLE tb_template_contratacao 
ADD COLUMN salario DECIMAL(10,2) NULL,
ADD COLUMN custo_hora DECIMAL(10,2) NULL,
ADD COLUMN vr DECIMAL(10,2) NULL,
ADD COLUMN va DECIMAL(10,2) NULL,
ADD COLUMN assistencia_medica DECIMAL(10,2) NULL,
ADD COLUMN ajuda_de_custo DECIMAL(10,2) NULL,
ADD COLUMN mobilidade DECIMAL(10,2) NULL,
ADD COLUMN educacao DECIMAL(10,2) NULL,
ADD COLUMN remuneracao_total DECIMAL(10,2) NULL;