<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ApiClient.Domain\ApiClient.Domain.csproj" />
    <ProjectReference Include="..\Colaboracao.Core\Colaboracao.Core.csproj" />
    <ProjectReference Include="..\Colaboracao.Initializer\Colaboracao.Initializer.csproj" />
    <ProjectReference Include="..\GeraCargaMock\GeraCargaMock.csproj" />
    <ProjectReference Include="..\Colaboracao.Infra\Colaboracao.Infra.csproj" />
    <ProjectReference Include="..\Core.DomainModel\Core.Domain.csproj" />
    <ProjectReference Include="..\Colaboracao.Shared.CargaCore.Domain\Colaboracao.Shared.CargaCore.Domain.csproj" />
    <ProjectReference Include="..\RotinasBackoffice.Domain\RotinasBackoffice.Domain.csproj" />
  </ItemGroup>
</Project>