INSERT INTO tb_funcionalidade_sistema
(id, descricao)
VALUES
(61, 'MAPA_DE_RELACIONAMENTO_VISUALIZAR'),
(62, 'MAPA_DE_RELACIONAMENTO_CRIAR'),
(63, 'MAPA_DE_RELACIONAMENTO_EDITAR'),
(64, 'MAPA_DE_RELACIONAMENTO_EXCLUIR'),
(65, 'MAPA_DE_RELACIONAMENTO_VCX_VISUALIZAR'),
(66, 'MAPA_DE_RELACIONAMENTO_VCX_CRIAR'),
(67, 'MAPA_DE_RELACIONAMENTO_VCX_EDITAR'),
(68, 'MAPA_DE_RELACIONAMENTO_VCX_EXCLUIR'),
(69, 'FEEDBACK360_GERAL'),
(70, 'FEEDBACK360_ADMIN');