export interface RouteInfo {
  path: string;
  isFlutterflow: boolean;
}

export const flutterflowRouteMap: { [key: string]: RouteInfo } = {

  //Rotas internas
  "cadastro_colaborador": { path: "colaboradores", isFlutterflow: false },
  
  //Rotas flutterflow
  "timesheet": { path: "timesheet", isFlutterflow: true },
  "timesheet_react": { path: "timesheet", isFlutterflow: false },
  "home_builder": { path: "home-builder", isFlutterflow: false },
  "dados_pessoais": { path: "dadospessoais", isFlutterflow: true },
  "perfil_360": { path: "cvdigital", isFlutterflow: true },
  "reembolso": { path: "reembolso", isFlutterflow: false },
  "mapa_alocacao": { path: "alocacoes", isFlutterflow: true },
  "cadastro_projeto": { path: "mapa/listadeprojetos", isFlutterflow: true },
  "pdi": { path: "novopdi", isFlutterflow: true },
  "okr": { path: "okr", isFlutterflow: true },
  "gestao_beneficios": { path: "gestao/beneficios", isFlutterflow: true },
  "match_competencias": { path: "sumario/competencias/new", isFlutterflow: true },
  "holerites": { path: "meu-holerite", isFlutterflow: false },
  "painel_remuneracao_4sys": { path: "default", isFlutterflow: true },
  "integracao_contabil": { path: "integracao-contabil", isFlutterflow: false },
  "jornada_projetos": { path: "default", isFlutterflow: true },
  "nossa_estrutura_sobre_foursys": { path: "default", isFlutterflow: true },
  "cadastros": { path: "default", isFlutterflow: true },
  "laboratorio": { path: "default", isFlutterflow: true },
  "sobre_mim": { path: "default", isFlutterflow: true },
  "mapa_demografico": { path: "sumario", isFlutterflow: true },
  "contrato_4sys": { path: "default", isFlutterflow: true },
  "portal_carreiras": { path: "vagas/portal", isFlutterflow: true },
  "gestao_perfis": { path: "gestaodealocados/perfis", isFlutterflow: true },
  "sustentabilidade_sobre_foursys": { path: "default", isFlutterflow: true },
  "indique_parceiros": { path: "default", isFlutterflow: true },
  "painel_alocados": { path: "gestaodealocados/painel", isFlutterflow: true },
  "book_colaborador": { path: "book/colaborador", isFlutterflow: true },
  "suporte": { path: "ajuda", isFlutterflow: true },
  "gestao_clientes_projetos": { path: "clientes", isFlutterflow: true },
  "iniciativas_lab": { path: "default", isFlutterflow: true },
  "reembolso_parametrizacao": { path: "reembolso/parametros", isFlutterflow: true },
  "beneficios_4sys": { path: "default", isFlutterflow: true },
  "pdi_minha_jornada": { path: "pdijornada", isFlutterflow: false },
  "pdi_minha_equipe": { path: "pdiequipe", isFlutterflow: false },
  "pdi_orquestracao": { path: "pdiorquestracao", isFlutterflow: false },
  "competencias": { path: "gestaodecompetencias", isFlutterflow: true },
  "simulador_custos_projetos": { path: "default", isFlutterflow: true },
  "ideias_lab": { path: "default", isFlutterflow: true },
  "minha_empresa": { path: "default", isFlutterflow: true },
  "fale_socios_4sys": { path: "default", isFlutterflow: true },
  "prestador": { path: "meu-faturamento", isFlutterflow: false },
  "integracao_folha_ponto": { path: "folha/integracao", isFlutterflow: true },
  "gestao_parcerias": { path: "gestao/parceria", isFlutterflow: false },
  "mapa_demografico_sobre_foursys": { path: "default", isFlutterflow: true },
  "manual_profile": { path: "default", isFlutterflow: true },
  "conciliacao_folha_pagamento": { path: "folha/conciliacao", isFlutterflow: true },
  "prestador_gestao": { path: "gestao-notas-fiscais", isFlutterflow: false },
  "indique_negocios": { path: "default", isFlutterflow: true },
  "ferias_4sys": { path: "default", isFlutterflow: true },
  "simulador_custos": { path: "default", isFlutterflow: true },
  "meu_progresso": { path: "default", isFlutterflow: true },
  "indique_colaborador": { path: "vagas/indicadas", isFlutterflow: true },
  "sobre_foursys": { path: "default", isFlutterflow: true },
  "showroom_lab": { path: "default", isFlutterflow: true },
  "gestao_outplacement_dashboard": { path: "default", isFlutterflow: true },
  "gestao_gestores_projetos": { path: "default", isFlutterflow: true },
  "tabela_fipe": { path: "default", isFlutterflow: true },
  "gestao_perfis_oportunidades": { path: "default", isFlutterflow: true },
  "bot_analytics_dashboard": { path: "default", isFlutterflow: true },
  "mapa_visitas": { path: "leads", isFlutterflow: true },
  "folha_de_pagamento": { path: "default", isFlutterflow: true },
  "gestao_contratacao_dashboard": { path: "default", isFlutterflow: true },
  "loja_foursys_sobre_foursys": { path: "default", isFlutterflow: true },
  "acumule_coins": { path: "default", isFlutterflow: true },
  "configuracoes": { path: "default", isFlutterflow: true },
  "precificacao": { path: "default", isFlutterflow: true },
  "jornada_alocados": { path: "default", isFlutterflow: true },
  "gestao": { path: "default", isFlutterflow: true },
  "felizometro": { path: "sentimentohoje", isFlutterflow: false },
  "maverick": { path: "dashboard-comercial", isFlutterflow: false },
  "dashboard_comercial": { path: "dashboard-comercial", isFlutterflow: false },
  "gestao_gestores": { path: "gestaodealocados/gestores", isFlutterflow: true },
  "precificacao_projetos": { path: "default", isFlutterflow: true },
  "dashboard": { path: "default", isFlutterflow: true },
  "solucoes": { path: "default", isFlutterflow: true },
  "repasse_conhecimento": { path: "default", isFlutterflow: true },
  "logas_paletas_sobre_foursys": { path: "default", isFlutterflow: true },
  "gestao_vagas": { path: "vagas/dashboard", isFlutterflow: true },
  "gestao_vagas_candidatos": { path: "vagas/candidatos", isFlutterflow: true },
  "gestao_clientes": { path: "gestaodealocados", isFlutterflow: true },
  "premios_sobre_foursys": { path: "default", isFlutterflow: true },
  "acompanhe_sobre_foursys": { path: "default", isFlutterflow: true },
  "rubricas": { path: "rubricas", isFlutterflow: true },
  "simulador_recrutamento": { path: "/simulador", isFlutterflow: false },
  "admissao_digital": { path: "/recrutamento/admissao", isFlutterflow: false },
  "gestao_desempenho_rh": { path: "gestao-desempenho-rh", isFlutterflow: false },
  "gestao_desempenho_gestor": { path: "gestao-desempenho-gestor", isFlutterflow: false },
  "gestao_desempenho_colaborador": { path: "gestao-desempenho-colaborador", isFlutterflow: false },
  "parametrizacao_recrutamento": { path: "recrutamento/parametrizacao", isFlutterflow: false },
  "dashboard_recrutamento": { path: "recrutamento/dashboard", isFlutterflow: false },
  "dashboard_jornadas": { path: "dashboard_jornadas", isFlutterflow: false },
  "remessa_cnab": { path: "reembolso/remessa-cnab", isFlutterflow: false },
  "comunicacao": { path: "comunicacao", isFlutterflow: false },
  "mapa_relacionamento": { path: "mapa-relacionamento", isFlutterflow: false },
  "agendas_comerciais": { path: "agendas-comerciais", isFlutterflow: false },
  "permissionamento": { path: "permissionamento", isFlutterflow: false },
  "simulador": { path: "simulador", isFlutterflow: false },
  "feedback360": { path: "feedback360", isFlutterflow: false },
  "gestao_vagas_metricas": { path: "recrutamento/dashboard", isFlutterflow: false },
  "candidaturasfmu": { path: "recrutamento/candidaturasfmu", isFlutterflow: false }
};
