CREATE TABLE tb_feriado (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    data DATE NOT NULL,
    nome VARCHAR(255) NOT NULL,
    tipo ENUM('NACIONAL', 'ESTADUAL', 'MUNICIPAL') NOT NULL,
    ativo BOOLEAN NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
