<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Colaboracao.Core\Colaboracao.Core.csproj" />
    <ProjectReference Include="..\Colaboracao.Helper\Colaboracao.Helper.csproj" />
    <ProjectReference Include="..\Core.DomainModel\Core.Domain.csproj" />
    <ProjectReference Include="..\DataTransferObject.Domain\DataTransferObject.Domain.csproj" />
    <ProjectReference Include="..\Apontamento.Infra\Apontamento.Infra.csproj" />
    <ProjectReference Include="..\Foursys.Domain\Foursys.Domain.csproj" />
    <ProjectReference Include="..\Usuario.Domain\Usuario.Domain.csproj" />
    <ProjectReference Include="..\Firebase.Domain\Firebase.Domain.csproj" />
    <ProjectReference Include="..\Logs.Infra\Logs.Infra.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
  </ItemGroup>
</Project>