<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.2.2" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.400.120" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
    <ProjectReference Include="..\ApiClient.Domain\ApiClient.Domain.csproj" />
    <ProjectReference Include="..\Colaboracao.Helper\Colaboracao.Helper.csproj" />
  </ItemGroup>
</Project>