<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Repositories\Holerite\**" />
    <Compile Remove="Repositories\Softskill\**" />
    <Compile Remove="Repositories\Usuario\Constantes\**" />
    <EmbeddedResource Remove="Repositories\Holerite\**" />
    <EmbeddedResource Remove="Repositories\Softskill\**" />
    <EmbeddedResource Remove="Repositories\Usuario\Constantes\**" />
    <None Remove="Repositories\Holerite\**" />
    <None Remove="Repositories\Softskill\**" />
    <None Remove="Repositories\Usuario\Constantes\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.4.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySql.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Dapper" Version="2.1.28" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Colaboracao.Helper\Colaboracao.Helper.csproj" />
    <ProjectReference Include="..\Colaboracao.Core\Colaboracao.Core.csproj" />
    <ProjectReference Include="..\Core.DomainModel\Core.Domain.csproj" />
    <ProjectReference Include="..\DataTransferObject.Domain\DataTransferObject.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Repositories\Usuario\" />
  </ItemGroup>
</Project>