AWSTemplateFormatVersion: 2010-09-09
Description: IaC Architectural Resources
Parameters:
  Env:
    Default: prd
    Type: String
  HostName:
    Default: colaborador-api
    Type: String
  PathPattern:
    Default: /api/BancoDeTalentos/*
    Type: String
  Priority:
    Default: 1513
    Type: String
  ProxyHostName:
    Default: api
    Type: String
Resources:
  Stack:
    Properties:
      Parameters:
        Env:
          Fn::Sub: ${Env}
        HostName:
          Fn::Sub: ${HostName}
        PathPattern:
          Fn::Sub: ${PathPattern}
        Priority:
          Fn::Sub: ${Priority}
        ProxyHostName:
          Fn::Sub: ${ProxyHostName}
        StackName:
          Fn::Sub: ${AWS::StackName}
      TemplateURL: https://fsys2-bucket-cfn-prd.s3.amazonaws.com/alb-listener-rule-template.yaml
    Type: AWS::CloudFormation::Stack
