AWSTemplateFormatVersion: 2010-09-09
Description: IaC Architectural Resources
Parameters:
  AwsProfile:
    AllowedValues:
    - fsys2-production
    Type: String
  Env:
    Default: prd
    Type: String
  Project:
    Default: colaborador-api
    Type: String
Resources:
  Stack:
    Properties:
      Parameters:
        AwsProfile:
          Fn::Sub: ${AwsProfile}
        Env:
          Fn::Sub: ${Env}
        Project:
          Fn::Sub: ${Project}
        StackName:
          Fn::Sub: ${AWS::StackName}
      TemplateURL: https://fsys2-bucket-cfn-prd.s3.amazonaws.com/ecs-service-template.yaml
    Type: AWS::CloudFormation::Stack
