CREATE TABLE IF NOT EXISTS tb_template_contratacao (
    id CHAR(36) NOT NULL PRIMARY KEY COMMENT 'ID único do template (GUID)',
    tb_colaborador_codigo_interno_colaborador_analista VARCHAR(36) NULL COMMENT 'Código interno do colaborador analista (GUID)',
    tb_colaborador_codigo_interno_colaborador VARCHAR(36) NULL COMMENT 'Código interno do colaborador (GUID)',
    tb_candidato_vaga_id varchar(36) NOT NULL COMMENT 'ID da candidatura (referência para tb_candidato_vaga)',
    cargo VARCHAR(255) NOT NULL COMMENT 'Cargo do colaborador',
    data_inicio DATE NULL COMMENT 'Data de início do contrato',
    horario_jornada VARCHAR(100) NULL COMMENT 'Horário da jornada de trabalho',
    tipo_horario_jornada VARCHAR(50) NULL COMMENT 'Tipo do horário de jornada (Integral, Reduzida, etc.)',
    tamanho_camiseta VARCHAR(10) NULL COMMENT 'Tamanho da camiseta (P, M, G, GG, etc.)',
    hardware TEXT NULL COMMENT 'Especificações de hardware necessárias',
    softwares_necessarios TEXT NULL COMMENT 'Softwares necessários para o trabalho',
    softwares_ec TEXT NULL COMMENT 'Softwares específicos da empresa',
    tb_colaborador_codigo_interno_colaborador_superior_imediato VARCHAR(36) NULL COMMENT 'Código interno do superior imediato (GUID)',
    email_pessoal VARCHAR(255) NULL COMMENT 'Email pessoal do colaborador',
    email_corporativo VARCHAR(255) NULL COMMENT 'Email corporativo do colaborador',
    login_rede VARCHAR(100) NULL COMMENT 'Login de rede do colaborador',
    tipo_login_rede VARCHAR(50) NULL COMMENT 'Tipo de login de rede',
    tipo_maquina VARCHAR(100) NULL COMMENT 'Tipo de máquina/equipamento',
    observacoes_acesso_usuario TEXT NULL COMMENT 'Observações sobre acesso do usuário',
    grupo_email_contrato VARCHAR(255) NULL COMMENT 'Grupo de email para contrato',
    observacoes_aprovador_acessos TEXT NULL COMMENT 'Observações do aprovador sobre acessos',
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Data de criação do registro',
    data_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Data da última alteração do registro',
    ativo TINYINT(1) DEFAULT 1 COMMENT 'Indica se o registro está ativo (1) ou inativo (0)',
    FOREIGN KEY (tb_candidato_vaga_id) REFERENCES tb_candidato_vaga(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (tb_colaborador_codigo_interno_colaborador) REFERENCES tb_colaborador(codigo_interno_colaborador) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (tb_colaborador_codigo_interno_colaborador_analista) REFERENCES tb_colaborador(codigo_interno_colaborador) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (tb_colaborador_codigo_interno_colaborador_superior_imediato) REFERENCES tb_colaborador(codigo_interno_colaborador) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='Tabela para armazenar templates de contratação com todos os campos necessários';