CREATE TABLE tb_cidadania (
  id INT PRIMARY KEY AUTO_INCREMENT,
  descricao VARCHAR(255) NOT NULL
);

INSERT INTO tb_cidadania (descricao) VALUES
('Afegã / Afegão'),
('Africana / Africano'),
('Albanesa / Albanês'),
('Alemã / Alemão'),
('Andorrana / Andorrano'),
('Angolana / Angolano'),
('Antilhana / Antilhano'),
('Argelina / Argelino'),
('Argentina / Argentino'),
('Armênia / Armênio'),
('Arubana / Arubano'),
('Australiana / Australiano'),
('Austríaca / Austríaco'),
('Azerbaijana / Azerbaijano'),
('Bahamense'),
('Bangladeshiana / Bangladeshiano'),
('Barbadiana / Barbadiano'),
('Belga'),
('Belizenha / Belizenho'),
('Beninense'),
('Bielorrussa / Bielorrusso'),
('Boliviana / Boliviano'),
('Bósnia / Bósnio'),
('Botsuanesa / Botsuanês'),
('Brasileira / Brasileiro'),
('Britânica / Britânico'),
('Bruneana / Bruneano'),
('Búlgara / Búlgaro'),
('Burquinense'),
('Burundiana / Burundiano'),
('Butanesa / Butanês'),
('Cabo-verdiana / Cabo-verdiano'),
('Camaronesa / Camaronês'),
('Cambojiana / Cambojiano'),
('Canadense'),
('Catariana / Catariano'),
('Cazaque / Cazaquista'),
('Chadeana / Chadeano'),
('Chilena / Chileno'),
('Chinesa / Chinês'),
('Cipriota'),
('Colombiana / Colombiano'),
('Congolesa / Congolês'),
('Coreana / Coreano'),
('Costarriquenha / Costarriquenho'),
('Croata'),
('Cubana / Cubano'),
('Curaçauense'),
('Dinamarquesa / Dinamarquês'),
('Dominicana / Dominicano'),
('Egípcia / Egípcio'),
('Emiradense'),
('Equatoriana / Equatoriano'),
('Eritreia / Eritreu'),
('Eslovaca / Eslovaco'),
('Eslovena / Esloveno'),
('Espanhola / Espanhol'),
('Estoniana / Estoniano'),
('Etíope'),
('Fijiana / Fijiano'),
('Filipina / Filipino'),
('Finlandesa / Finlandês'),
('Francesa / Francês'),
('Gabonesa / Gabonês'),
('Galega / Galego'),
('Gambiana / Gambiano'),
('Ganesa / Ganês'),
('Georgiana / Georgiano'),
('Gibraltina / Gibraltino'),
('Grega / Grego'),
('Guatemalteca / Guatemalteco'),
('Guianesa / Guianês'),
('Guianense'),
('Guineana / Guineano'),
('Guineense'),
('Haitiana / Haitiano'),
('Hondurenha / Hondurenho'),
('Húngara / Húngaro'),
('Iemenita'),
('Indiana / Indiano'),
('Indonésia / Indonésio'),
('Inglesa / Inglês'),
('Iraniana / Iraniano'),
('Iraquiana / Iraquiano'),
('Irlandesa / Irlandês'),
('Islandesa / Islandês'),
('Israelense'),
('Italiana / Italiano'),
('Jamaicana / Jamaicano'),
('Japonesa / Japonês'),
('Jordaniana / Jordaniano'),
('Kuwaitiana / Kuwaitiano'),
('Laociana / Laociano'),
('Letã / Letão'),
('Libanesa / Libanês'),
('Libéria / Liberiano'),
('Líbia / Líbio'),
('Liechtensteinense'),
('Lituana / Lituano'),
('Luxemburguesa'),
('Macedônia / Macedônio'),
('Madagascarense'),
('Malaia / Malaio'),
('Malauiana / Malauiano'),
('Maldiva / Maldivo'),
('Malinesa / Malinês'),
('Maltese'),
('Marfinense'),
('Marroquina / Marroquino'),
('Mauriciana / Mauriciano'),
('Mauritana / Mauritano'),
('Mexicana / Mexicano'),
('Mianmarense'),
('Moldava / Moldavo'),
('Monegasca / Monegasco'),
('Mongol'),
('Montenegrina / Montenegrino'),
('Moçambicana / Moçambicano'),
('Namibiana / Namibiano'),
('Nauruana / Nauruano'),
('Nepalesa / Nepalês'),
('Neozelandesa / Neozelandês'),
('Nicaraguense'),
('Nigeriana / Nigeriano'),
('Nigerina / Nigerino'),
('Norueguesa / Norueguês'),
('Omã / Omanense'),
('Palestina / Palestino'),
('Panamenha / Panamenho'),
('Papua-Nova-Guineense'),
('Paquistanesa / Paquistanês'),
('Paraguaia / Paraguaio'),
('Peruana / Peruano'),
('Polonesa / Polonês'),
('Portuguesa / Português'),
('Porto-riquenha / Porto-riquenho'),
('Queniana / Queniano'),
('Quirguiz / Quirguiz'),
('Quiribati / Quiribati'),
('Romena / Romeno'),
('Russa / Russo'),
('Ruandesa / Ruandês'),
('Saltenha / Saltenho'),
('Salvadoreña / Salvadoreño'),
('Samoana / Samoano'),
('Santa-lucense'),
('São-cristovense'),
('São-marinense'),
('São-tomense'),
('Saudita'),
('Senegalesa / Senegalês'),
('Sérvia / Sérvio'),
('Seichelense'),
('Serra-leonesa / Serra-leonês'),
('Singapuriana / Singapuriano'),
('Síria / Sírio'),
('Somaliana / Somali'),
('Sul-africana / Sul-africano'),
('Sudanesa / Sudanês'),
('Sueca / Sueco'),
('Suíça / Suíço'),
('Surinamesa / Surinamês'),
('Tailandesa / Tailandês'),
('Taitiana / Taitiano'),
('Tanzaniana / Tanzaniano'),
('Tcheca / Tcheco'),
('Togolesa / Togolês'),
('Tongalesa / Tongalês'),
('Trinidadiana / Trinidadiano'),
('Tunisiana / Tunisiano'),
('Turca / Turco'),
('Turcomena / Turcomeno'),
('Ucraniana / Ucraniano'),
('Ugandense'),
('Uruguaia / Uruguaio'),
('Uzbeque'),
('Venezuelana / Venezuelano'),
('Vietnamita'),
('Zambiana / Zambiano'),
('Zimbabuense');