namespace TemplateOrg.Constantes
{
    public enum TemplateOrgParametroEnum
    {
        RESET_SENHA_ORG_SSO,
        CADASTRO_NOVO_USUARIO_SENHA,
        CADASTRO_NOVO_USUARIO_SSO,
        TOKEN_ACESSO_EMAIL,
        REPROVACAO_APONTAMENTO_HORAS,
        NOTIFICACAO_APONTAMENTOS_STATUS_PENDENTE,
        NOTIFICA_GESTOR_APONTAMENTOS_STATUS_PENDENTE,
        CV_EM_MASSA,
        APONTAMENTO_EXCEDENTE,
        NOTIFICACAO_PJ_EMISSAO,
        CANAL_DENUNCIA,
        NOTIFICACAO_COMUNICACAO_OFICIAL,
        NOTIFICACAO_COMUNICACAO_COMUNIDADE
    }
}